name: Go

on:
  workflow_dispatch:
    inputs:
      pktvisor_tag:
        description: 'pktvisor agent docker tag to package'
        required: true
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  trigger-build-services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            agent:
              - 'agent/**'
              - 'cmd/agent/**'
            orb:
              - 'fleet/**'
              - 'cmd/fleet/**'
              - 'policies/**'
              - 'cmd/policies/**'
              - 'sinks/**'
              - 'cmd/sinks/**'
              - 'sinker/**'
              - 'cmd/sinker/**'
              - 'ui/**'
      - name: Set branch name
        shell: bash
        run: |
          echo "BRANCH_NAME=develop" >> $GITHUB_ENV

      - name: Generate ref tag (develop)
        run: |
          echo "REF_TAG=develop" >> $GITHUB_ENV

      - name: Append suffix on VERSION file for develop build
        run: |
          echo "`cat ${{github.workspace}}/VERSION`-${{ env.REF_TAG }}" > VERSION

      - name: Get VERSION
        run: |
          echo "VERSION=`cat ${{github.workspace}}/VERSION`" >> $GITHUB_ENV

      - name: Debug VERSION
        run: echo ${{ env.VERSION }}

      - name: Get short commit hash to a variable
        id: commit_hash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    outputs:
      should-build-agent: ${{ steps.changes.outputs.agent }}
      should-build-orb: ${{ steps.changes.outputs.orb }}

  test-agent:
    runs-on: ubuntu-latest
    needs: trigger-build-services
    if: ${{ needs.trigger-build-services.outputs.should-build-agent == 'true' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Go unit tests
        run: SERVICE=agent make test_service

  test-fleet:
    runs-on: ubuntu-latest
    needs: trigger-build-services
    if: ${{ needs.trigger-build-services.outputs.should-build-orb == 'true' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Go unit tests
        run: SERVICE=fleet make test_service

  test-policies:
    runs-on: ubuntu-latest
    needs: trigger-build-services
    if: ${{ needs.trigger-build-services.outputs.should-build-orb == 'true' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Go unit tests
        run: SERVICE=policies make test_service

  test-sinks:
    runs-on: ubuntu-latest
    needs: trigger-build-services
    if: ${{ needs.trigger-build-services.outputs.should-build-orb == 'true' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Go unit tests
        run: SERVICE=sinks make test_service

  test-sinker:
    runs-on: ubuntu-latest
    needs: trigger-build-services
    if: ${{ needs.trigger-build-services.outputs.should-build-orb == 'true' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Go unit tests
        run: SERVICE=sinker make test_service

  test-ui:
    runs-on: ubuntu-latest
    needs: trigger-build-services
    if: ${{ needs.trigger-build-services.outputs.should-build-orb == 'true' }}
    steps:
      - uses: actions/checkout@v2
      - name: Test UI
        run: make test_ui

  package-agent:
    needs: test-agent
    runs-on: ubuntu-latest
    if: ${{ needs.trigger-build-services.outputs.should-build-agent == 'true' }}
    steps:
      - uses: actions/checkout@v2
      - name: Debug values
        run: |
          echo ${{ jobs.trigger-build-services.env.VERSION }}
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo ${{ github.event.inputs.pktvisor_tag }}

      - name: Build orb-agent
        shell: bash
        env:
          IMAGE_NAME: ns1labs/orb-agent
        run: |
          if [ "${{ github.event.inputs.pktvisor_tag }}" == "" ]; then
            make agent
            make agent_debug
          else
            PKTVISOR_TAG=${{ github.event.inputs.pktvisor_tag }} make agent
            PKTVISOR_TAG=${{ github.event.inputs.pktvisor_tag }} make agent_debug
          fi

      # If it is a Pull Request, only build to make sure that everything is running
      # If it is not a pull request, then should publish the image built
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push agent container
        if: github.event_name != 'pull_request'
        run: |
          docker push -a ns1labs/orb-agent

  package-fleet:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.trigger-build-services.outputs.should-build-orb == 'true' }}
    steps:
      - uses: actions/checkout@v2

      - name: Debug values
        run: | 
          echo ${{ env.VERSION }}
          echo ${{ jobs.trigger-build-services.env.VERSION }}
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build service containers
        run: SVC=fleet make docker

      # If it is a Pull Request, only build to make sure that everything is running
      # If it is not a pull request, then should publish the image built

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push service containers
        if: github.event_name != 'pull_request'
        run: docker push -a ns1labs/orb-fleet

  package-policies:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.trigger-build-services.outputs.should-build-orb == 'true' }}
    steps:
      - uses: actions/checkout@v2

      - name: Debug values
        run: |
          echo ${{ env.VERSION }}
          echo ${{ jobs.trigger-build-services.env.VERSION }}
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build service containers
        run: SVC=policies make docker

      # If it is a Pull Request, only build to make sure that everything is running
      # If it is not a pull request, then should publish the image built

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push service containers
        if: github.event_name != 'pull_request'
        run: docker push -a ns1labs/orb-policies

  package-sinker:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.trigger-build-services.outputs.should-build-orb == 'true' }}
    steps:
      - uses: actions/checkout@v2

      - name: Debug values
        run: |
          echo ${{ env.VERSION }}
          echo ${{ jobs.trigger-build-services.env.VERSION }}
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build service containers
        run: SVC=sinker make docker

      # If it is a Pull Request, only build to make sure that everything is running
      # If it is not a pull request, then should publish the image built

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push service containers
        if: github.event_name != 'pull_request'
        run: docker push -a ns1labs/orb-sinker

  package-sinks:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.trigger-build-services.outputs.should-build-orb == 'true' }}
    steps:
      - uses: actions/checkout@v2

      - name: Debug values
        run: |
          echo ${{ env.VERSION }}
          echo ${{ jobs.trigger-build-services.env.VERSION }}
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build service containers
        run: SVC=sinks make docker

      # If it is a Pull Request, only build to make sure that everything is running
      # If it is not a pull request, then should publish the image built

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push service containers
        if: github.event_name != 'pull_request'
        run: docker push -a ns1labs/orb-sinks

  package-ui:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.trigger-build-services.outputs.should-build-orb == 'true' }}
    steps:
      - uses: actions/checkout@v2

      - name: Build orb-ui
        env:
          IMAGE_NAME: ns1labs/orb-ui
        run: |
          make ui

      # If it is a Pull Request, only build to make sure that everything is running
      # If it is not a pull request, then should publish the image built
      - name: Commit orb-ui-live on orb-live repo develop
        if: github.event_name != 'pull_request'
        run: |
          git config --global user.email "${{secrets.GH_ORB_EMAIL}}"
          git config --global user.name "${{secrets.GH_ORB_USER}}"
          git config --global credential.helper cache
          git clone -b develop https://${{secrets.GH_ORB_USER}}:${{secrets.GH_ORB_ACCESS_TOKEN}}@github.com/ns1labs/orb-live.git          
          cd orb-live
          cp -rf ../ui .
          cp -rf ../VERSION .
          echo "${{ steps.commit_hash.outputs.sha_short }}" > COMMIT_HASH          
          git add .
          git commit -m "[NS1 Orb Bot] Update Orb Live UI for develop"
          git push origin develop

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push ui container
        if: github.event_name != 'pull_request'
        run: |
          docker push -a ns1labs/orb-ui

  publish-orb-live-stg:
    needs:
      - package-fleet
      - package-policies
      - package-sinker
      - package-sinks
      - package-ui

    runs-on: ubuntu-latest
    # if this is a push into one of our main branches (rather than just a pull request), we will also package
    if: github.event_name != 'pull_request'

    steps:
      - uses: actions/checkout@v2

      - name: Debug values
        run: |
          echo ${{ jobs.trigger-build-services.env.VERSION }}
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo ${{ github.event.inputs.pktvisor_tag }}
        env:
          VERSION: ${{ jobs.trigger-build-services.env.VERSION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Commit image tag on orb-live-manifest environment dev
        run: |
          git config --global user.email "${{secrets.GH_ORB_EMAIL}}"
          git config --global user.name "${{secrets.GH_ORB_USER}}"
          git config --global credential.helper cache
          git clone https://${{secrets.GH_ORB_USER}}:${{secrets.GH_ORB_ACCESS_TOKEN}}@github.com/ns1labs/orb-live-manifest.git
          cd orb-live-manifest/stg
          mv values.yaml .template/values.old
          cat .template/values.yaml.tpl >> values.yaml
          sed -i -e "s/IMAGE_TAG/${{ env.VERSION }}-${{ steps.commit_hash.outputs.sha_short }}/g" values.yaml
          git add values.yaml
          git add .template/values.old
          git commit -m "[NS1 Orb Bot] Update image tag on stg environment"
          git push origin main
